mypomoc/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from skusam import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:    url(r'^rango/register/$', views.register, name='register'),
    url(r'^rango/login/$', views.user_login, name='login'),
   
  
    #url(r'^rango/account/(?P<user_id>\d+)$', views.front, name='front'),
    url(r'^rango/account/$',views.accountprofile,name='frontpage'),
    url(r'^rango/study/$',views.study,name='studypage'),
    url(r'^rango/problem/$',views.problems,name='problempage'),

    url(r'^rango/study/(?P<category_name_url>\w+)/$', views.category, name='category'),
    url(r'^rango/study/(?P<category_name_url>\w+)/article/new/$', views.ArticleCreateView.as_view(), name='article-new'),
    #url(r'^rango/account/$',views.front,name=''),
    url(r'^rango/account/personalprofile/(?P<pk>\d+)/$', views.UserListView.as_view(),name='personalprofil-list',),
    url(r'^rango/account/userprofile/edit/(?P<pk>\d+)/$', views.UpdateUserprofileView.as_view(),name='userprofile-edit',),
    url(r'^rango/account/userprofile/(?P<pk>\d+)/$', views.UserprofileListView.as_view(),name='userprofile-list',),
    url(r'^rango/account/personalprofile/edit/(?P<pk>\d+)/$', views.UpdateUserView.as_view(),name='personalprofil-edit',),
    url(r'^rango/account/groups/(?P<pk>\d+)/$', views.UsergroupsListView.as_view(),name='usergroups-list',),
    url(r'^rango/account/accountbalance/(?P<pk>\d+)/$', views.AccountbalanceListView.as_view(),name='accountbalance-list',),
    url(r'^rango/account/accountbalance/edit/(?P<pk>\d+)/$', views.AccountbalanceListView.as_view(),name='accountbalance-edit',),
    url(r'^rango/account/groups/edit/(?P<pk>\d+)/$', views.UpdateUsergroupsView.as_view(),name='usergroups-edit',),
    url(r'^rango/account/address/edit/(?P<pk>\d+)$', views.UpdateUseraddressView.as_view(),name='address-edit',),
    url(r'^rango/account/password/edit/(?P<pk>\d+)/$', views.UpdatePasswordView.as_view(),name='password-edit',),
    url(r'^rango/register/$', views.register, name='register'),
   
    url(r'^rango/studyyy/(?P<slug>\w+)/$',views.CategoryDetailView.as_view(),name='article-view-category'),
    url(r'^rango/$', views.front, name='front'),
    url(r'^rango/studyy/nove/$',views.ArticleStudyListView.as_view(),name='article-view-pagin'),
    url(r'^rango/study/(?P<category_name_url>\w+)/article/(?P<pk>\d+)/$',views.ArticleDetailuserView.as_view(),name='article-view'),
    url(r'^rango/study/(?P<category_name_url>\w+)/article/(?P<pk>\d+)/voice$',views.ArticleVoicesUpdateView.as_view(),name='article-voices'),
    url(r'^rango/logout/$', views.user_logout, name='logout'),
    url(r'^rango/study/(?P<category_name_url>\w+)/article/delete/(?P<pk>\d+)/$', views.ArticleDeleteView.as_view(),name='article-delete'),
    url(r'^rango/study/(?P<category_name_url>\w+)/article/edit/(?P<pk>\d+)/$', views.ArticleUpdateView.as_view(),name='article-edit',),
    # url(r'^$', 'mypomoc.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', 'my_home', name='my_home',),
    url(r'^$', views.ListContactView.as_view(),name='contacts-list',), 
    url(r'^new$', views.CreateContactView.as_view(),name='contacts-new',),
    url(r'^edit/(?P<pk>\d+)/$', views.UpdateContactView.as_view(),name='contacts-edit',),
    #url(r'^$', views.ListContactView.as_view(),name='contacts-list',), 
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteContactView.as_view(),name='contacts-delete',),
    url(r'^admin/', include(admin.site.urls)),
    url(r'articles/(?P<pk>\d+)$',views.ArticleDetailView.as_view(),name='article_detail'),
  
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
  
    url(r'tags/(?P<title>\w+)$', views.TagDetailView.as_view(),name='tag_detail'),
    url(r'authors/(?P<username>\w+)$','view_author',name='view_author'),

    url(r'^accounts/logout/$','django.contrib.auth.views.logout',{'template_name': 'login.html'},),
    url(r'^articles/new$', views.ArticleCreateView.as_view(),name='article-new',),
   
    
    # url(r'/$', view_home_method, 'home_url_name'),
    # url(r'/services/$', view_services_method, 'services_url_name'),
    # url(r'/contact/$', view_contact_method, 'contact_url_name'),
)

skusam/models.py
import re
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    info=models.TextField(default='')
    overview=models.TextField(default='')
    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title
# Create your models here.
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    info=models.TextField()
    website = models.URLField(blank=True)
    balance=models.IntegerField(default=0)


    #picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username
class Address(models.Model):
    user = models.OneToOneField(User)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=150, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zip = models.CharField(max_length=15, blank=True)

    def __unicode__(self):
    	return '{0}, {1}'.format(self.address,self.city)

class Contact(models.Model):

    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)

    birthdate = models.DateField(blank=True,null=True)
    phone = models.CharField(max_length=25, blank=True)
    email = models.EmailField(blank=True)
    address = models.ForeignKey(Address, null=True)   
    def __unicode__(self):
    	return '{0}  {1} lived in {2}'.format(self.first_name,self.last_name,self.address)

class Tag(models.Model):
   'Tag model'
   title=models.CharField('tag title',max_length=2**6, unique=True)
   def __unicode__(self):
      return '#{0}'.format(self.title)
   def get_absolute_url(self):
      'returns absolute path for tag'
      return reverse('view_tag',kwargs={'tag_id':self.id})  

class Article(models.Model):
  'Article model'
  category = models.ForeignKey(Category)
  author=models.ForeignKey(User)
  pub_date=models.DateTimeField('published date',auto_now_add=True)
  title=models.CharField('Title',max_length=2**6)
  content=models.TextField()
  #data=models.CharField('este neviem',max_length=2**6)
  pattern=re.compile(r'#(?P<title>\w+)')
  tags=models.ManyToManyField('Tag',blank=True)
  voices=models.ManyToManyField('UserProfile',blank=True)
  
  def __unicode__(self):
     return '"{2}" at {1} by {0}'.format(self.author,self.pub_date,self.title)
  def get_absolute_url(self):
     'returns absolute path for article'   
     return reverse('view_article',kwargs={'article_id':self.id})
  # def save(self,**kwargs):
  #    'save the article'
  #    super(Article,self).save(self)
  #    tags=Article.pattern.findall(self.content)
  #    #select * from tag where title in ('tag1','tag2')
  #    tags_existing=list(Tag.objects.filter(title__in=tags))
  #    tags_existing_titles=[tag.title for tag in tags_existing]
  #    #append missing tags as newly created ones
  #    for tag in tags:
  #     # print('procesing '+tag)
  #      if tag not in  tags_existing_titles:
  #        tag_new=Tag.objects.create(title=tag)
  #        tags_existing.append(tag_new)
  #        #add tags directly as a list
  #        self.tags=tags_existing

skusam/views.py
from django.shortcuts import render,render_to_response,HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from skusam.models import Address,Article, Tag,Contact,Category,Page,UserProfile
from django.views.generic import CreateView,UpdateView,ListView,UpdateView,DeleteView,DetailView

from django.contrib.auth.models import User,Group

from django.contrib.auth import authenticate, login, logout
from skusam.forms import UserForm,UserProfileForm,UsergroupForm
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# @login_required
# def restricted(request):
#     return HttpResponse("Since you're logged in, you can see this text!")


# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/rango/')

def problems(request):
    return render(request,'problem_list.html',{})    

def study(request):
     # Obtain the context from the HTTP request.
    context = RequestContext(request)

    # Query for categories - add the list to our context dictionary.
    category_list = Category.objects.all()
    context_dict = {'categories': category_list}

    # The following two lines are new.
    # We loop through each category returned, and create a URL attribute.
    # This attribute stores an encoded URL (e.g. spaces replaced with underscores).
    for category in category_list:
        category.url = category.name.replace(' ', '_')

    # Render the response and return to the client.
    return render_to_response('study_list.html', context_dict, context)


def accountprofile(request):
     # Obtain the context from the HTTP request.
    context = RequestContext(request)

    # Query for categories - add the list to our context dictionary.
    category_list = Category.objects.all()
    context_dict = {'categories': category_list}

    # The following two lines are new.
    # We loop through each category returned, and create a URL attribute.
    # This attribute stores an encoded URL (e.g. spaces replaced with underscores).
    for category in category_list:
        category.url = category.name.replace(' ', '_')

    # Render the response and return to the client.
    return render_to_response('front_page.html', context_dict, context)

def front(request):
     # Obtain the context from the HTTP request.
    context = RequestContext(request)

    # Query for categories - add the list to our context dictionary.
    category_list = Category.objects.all()
    context_dict = {'categories': category_list}

    # The following two lines are new.
    # We loop through each category returned, and create a URL attribute.
    # This attribute stores an encoded URL (e.g. spaces replaced with underscores).
    for category in category_list:
        category.url = category.name.replace(' ', '_')

    # Render the response and return to the client.
    return render_to_response('index.html', context_dict, context)
def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)

def index(request):
    context = RequestContext(request)

    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {'categories': category_list}

    # Render the response and send it back!
    return render_to_response('index.html', context_dict, context)


def category(request, category_name_url):
    
        # Request our context from the request passed to us.
    context = RequestContext(request)
    

    # Change underscores in the category name to spaces.
    # URLs don't handle spaces well, so we encode them as underscores.
    # We can then simply replace the underscores with spaces again to get the name.
    category_name = category_name_url.replace('_', ' ')

    # Create a context dictionary which we can pass to the template rendering engine.
    # We start by containing the name of the category passed by the user.
    context_dict = {'category_name': category_name}

    try:
        # Can we find a category with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(name=category_name)

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    article_list=Article.objects.filter(category=category).order_by('title')
    paginator=Paginator(article_list, 10)
    page=request.GET.get('page')
    try:
        articlesss=paginator.page(page)
    except PageNotAnInteger:
        articlesss=paginator.page(1)
    except EmptyPage:
        articless=paginator.page(paginator.num_pages) 

    article_list=Article.objects.filter(category=category)
    pom=[]
    for item in article_list:
        count=item.voices.count()
        novy=[count,item]
        pom.append(novy)
    pom.sort()
    pom.reverse()
   
    context_dict['articlesss']=articlesss  
    
    context_dict['article_list']=[item[1] for item in pom[0:5]] 

    # Go render the response and return it to the client.
    return render_to_response('category.html', context_dict, context)


def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/rango/account/')
                #return render(request,'front.html',{})

            else:

skusam/templates/authors.html
{% extends 'base.html' %}
{% block title %}
<h1> All Users </h1>
{% endblock title %}

{% block content %}
<ul>
	{% for author in authors %}
	<li>
		<a href="{%url 'view_author' author.username %}">{{author.username}}</a>
	</li>
	{% endfor %}
</ul>
{%endblock content %}

skusam/templates/base.html
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">

    
    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

<style type="text/css">
 body {padding-top:60px; padding-bottom:40px;}
 .sidebar-nav{padding:9px 0;}

 @media (max-width:980px) {.navbar-text.pull-right {float:none;padding-left:5px;padding-right:5px;}}
 </style>
</head>
<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
       <div class="container">
           <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a class="brand" href="/rango/">Home</a>

           <div class="nav-collapse collapse">
               <ul class="nav pull-right">
                   {% if user.is_authenticated %}
                    <li class="navbar-text">Welcome, {{ user.username }}!</li>
                     <li><a href="/rango/account/">My account</a></li>
                    <li><a href="/rango/logout/">Logout</a></li>
                   {% else %}
                    <li><a href="/rango/register/">Register</a></li>
                    <li><a href="/rango/login/">Login</a></li>
                   {% endif %}
               </ul>
               <ul class="nav">
                   {% if user.is_authenticated %}
                    <li><a href="/rango/study/">Study</a></li>
                    <li><a href="/rango/forumlog/">Forum</a></li>
                    <li><a href="/rango/calcul/">Calculation</a></li>
                    <li><a href="/rango/problem/">Have you a problem?</a></li>
                   {% else %}
                   
                   <li><a href="/rango/artic/">Articles without logging</a></li>
                   <li><a href="/rango/forum/">Forum without logging</a></li>
                    {% endif %}
               </ul>
           </div>
           <!--/.nav-collapse -->
       </div>
   </div>
</div>


<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <!--- Empty for the timebeing -->{% block sidebar %}
            {% endblock %}
            </div>
            <!--/.well -->
             <div class="well sidebarr-nav">
                <!--- Empty for the timebeing -->{% block sidebarr %}
            {% endblock %}
            </div>
        </div>
   
        <!--/span-->
        <div class="span9">
            {% block body_block %}
            {% endblock %}
        </div>
        <!--/span-->
    </div>
    <!--/row-->
</div>
<!--/.fluid-container-->
<hr>
<footer>
    <div class="container">
        <p>&copy; M.S. 2014</p>
    </div>
</footer>


    <script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

skusam/templates/bases.html
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
       <div class="container">
           <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a class="brand" href="/rango/">Home</a>

           <div class="nav-collapse collapse">
               <ul class="nav pull-right">
                   {% if user.is_authenticated %}
                    <li class="navbar-text">Welcome, {{ user.username }}!</li>
                     <li><a href="/rango/account/">My account</a></li>
                    <li><a href="/rango/logout/">Logout</a></li>
                   {% else %}
                    <li><a href="/rango/register/">Register</a></li>
                    <li><a href="/rango/login/">Login</a></li>
                   {% endif %}
               </ul>
               <ul class="nav">
                   {% if user.is_authenticated %}
                    <li><a href="/rango/study/">Study</a></li>
                    <li><a href="/rango/forumlog/">Forum</a></li>
                    <li><a href="/rango/calcul/">Calculation</a></li>
                    <li><a href="/rango/problem/">Have you a problem?</a></li>
                   {% else %}
                   
                   <li><a href="/rango/artic/">Articles without logging</a></li>
                   <li><a href="/rango/forum/">Forum without logging</a></li>
                    {% endif %}
               </ul>
           </div>
           <!--/.nav-collapse -->
       </div>
   </div>
</div>


<div id="page">
    <div id="content">
          {%block body block%} {% endblock%}
    </div>
          
    <div id="sidebar">
            <div id="tbox1">
             {%block sidebar%} {% endblock%}
            </div>
            
    </div>

</div>
<!--/.fluid-container-->
<hr>
<footer>
    <div class="container">
        <p>&copy; M.S. 2014</p>
    </div>
</footer>


    <script src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

skusam/templates/category.html
{%extends 'base.html' %}

{% block body_block %}
    <div class="hero-unit">
      <h1>{{ category_name }}</h1>
    </div>
       
 
     <ul> <h2>Overview </h2>
      {{category.overview}}
     </ul>

     <ul> 
        <h2>Register of Articles:</h2> 
         
          {% if category.article_set.all %}  
          <table  border="5" width="80%"  cellpadding="2" >
            <thead> 
              <tr> 
                <th> ID of Article </th> <th> Title of Article</th> <th> Author</th><th> Voices</th> 
              </tr>
            </thead> 
            <tbody>
            {% for artic in articlesss%}
            <tr>
               <td><center>{{artic.id}}  </center></td>
               <td><ul><a href="{% url "article-view" pk=artic.id  category_name_url=category.name %}">{{ artic.title }}</a> </ul></td>
               <td> <center>{{artic.author}} </center></td>
               <td> <center>{{artic.voices.count}} </center></td>
            </tr>
            {% endfor %} 
            </tbody>
          </table>  
 
          <div class="pagination">
            <span class="step-links">
               {% if articlesss.has_previous %}
                 <a href= "?page={{ articlesss.previous_page_number }}">previous page &lt;&lt; </a>
               {% endif %}
 
               <span class="current">
                 &nbsp;Page {{ articlesss.number }} of {{articlesss.paginator.num_pages }}
               </span>
 
               {% if articlesss.has_next %}
                 <a href="?page={{ articlesss.next_page_number }}"> &gt;&gt; next page</a> 
               {% endif %}
            </span>
           </div>
                      
          {% else %}
             <strong>No articles currently in category: {{category_name}}.</strong>
          {% endif %}
    </ul>



     <ul>        
            {% if pages %} <h2>Useful links</h2>
            <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category: {{category_name}}.</strong>
            {% endif %}
     </ul>
{% endblock %}

{% block sidebar %}
<UL class="nav nav-list">
  <LI class="nav-header"><h3>Top Articles </h3></LI>
       
        {% if category.article_set.all %}  
          <ul>  
                {% for artic in article_list%}
                <li><a href="{% url "article-view" pk=artic.id  category_name_url=category.name %}">{{ artic.title }} </a> ({{artic.voices.count}})</li>
                {% endfor %}
        </ul>
        {% else %}
        <strong>No article at present.</strong>
        {% endif %}
</UL>


<UL class="nav nav-list"> </UL>
  <LI class="nav-header"><h3>Options </h3></LI>
  
  {% for groups in user.groups.filter %}
        {% for perm in groups.permissions.filter %}
           {% if 'Can add article' == perm.name %}
           
      <ul><h4><strong>with permission </strong></h4>
   
       <form action="{% url "article-new"  category_name_url=category.name %}" method='get'>
          <button type='submit' class="btn btn-primary"> add new article </button>
        </form>
       </ul> 
          {% endif%}

      {% endfor %}
 
{% endfor %}
 
 
{% endblock %}

{% block sidebarr %}
<UL class="nav nav-list"> </UL>
  <LI class="nav-header"><h3>Search </h3></LI>
<form action='' Method="post" >
  
Find article with the keyword: <BR><BR>

<INPUT TYPE="text" SIZE="10" MAXLENGTH="8"> <BR> 
<UL><INPUT TYPE="submit" VALUE="Find"></UL>
 
</form>

{% endblock %}

skusam/templates/categoryyy.html
{%extends 'base.html' %}

{% block body_block %}
    <div class="hero-unit">
      <h1>{{ category.name }}</h1>
    </div>
        
     <ul> 
        <h2>Articles</h2> 
         <h4><strong>If you have a permission to add new article you can do it :)</strong></h4>
          <ul>  <ul>
            <form action="{% url "article-new"  category_name_url=category.name %}" method='get'>
              <button type='submit' class="btn btn-primary"> add new article </button>
            </form>
          </ul></ul>   
           <a href="{% url "article-view-pagin"  %}">pozri</a>

  </ul>
              {% if category.article_set.all %}  bbggb
              {%endif%} 
               
             {% for arti in article_list %}

    <li>{{arti.title}} {{arti.author}} </li>

          {% endfor %}

{% if page_obj.has_previous %}
  <a href= "?page={{ page_obj.previous_page_number }}">previous page &lt;&lt; </a>
{% endif %}
 
<span class="current">
  &nbsp;Page {{ page_obj.number }} of {{paginator.num_pages }}
</span>
 
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}"> &gt;&gt; next page</a>
{% endif %}

        
      
      

  

     <ul>        
            {% if pages %} <h2>Useful links</h2>
            <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category: {{category_name}}.</strong>
            {% endif %}
     </ul>
{% endblock %}
{% block sidebar %}
<UL class="nav nav-list">
  <LI class="nav-header"><h3>Top Articles </h3></LI>
       
        {% if category.article_set.all %}  
          <ul> 
                {% for artic in category.article_set.all %}
                <li><a href="{% url "article-view" pk=artic.id  category_name_url=category.name %}">{{ artic.title }}</a></li>
                {% endfor %}
        </ul>
        {% else %}
        <strong>No article at present.</strong>
        {% endif %}

</UL>
  


{% endblock %}

skusam/templates/edit_article.html
{%extends "base.html" %}
{% block body_block %}

<div class="hero-unit">
  <font face='arial'  color='royalblue'>
  	<h3> {% if article.id %}
  	          You can edit the article now 
         {% else %}
              You can add new article now 
         {% endif %} 
         
    </h3> 
  </font>

<form action="{{ action }}"   method="POST">
    {% csrf_token %}
     <ul>   
       {{ form.as_ul }} 
     </ul>
  <button id="save_article"  class="btn btn-primary"  type="submit"> save article </button>
</form>
   <a href="/rango/study/{{ category.url }}">back to study</a>
</div>
{% endblock %}